### PR TITLE
Fix step size regulation for propagation without nonlinearity

### LINKED ISSUE #270: Turning off plasma and kerr in prop_capillary
Dear Chris,

I hope you're well!
I tried propagating a pulse with both ionisation and the kerr effect turned off by adding the arguments "plasma = false" and "kerr = false" in prop_capillary. When I use these individually, everything works. However, whenever I try to turn both off I get an error saying "'InexactError: trunc(Int64, NaN)' occurred while calling julia code" - should I be turning both of these off simultaneously with a different method?

Thanks for your help!
Maike

### PR DESCRIPTION
**Pull request by chrisbrahms**
This makes the step size controller in `RK45.jl` deal with a zero-valued error more gracefully (by increasing the step size by some fixed large amount), instead of throwing out `NaN`s and breaking the propagation.

Without this change, the following code errors:
```julia
using Luna

a = 75e-6
flength = 0.55
gas = :He
pressure = 10

λ0 = 1030e-9
τfwhm = 10e-15
energy = 45e-6

λlims = (160e-9, 4e-6)
trange = 0.5e-12

duv = prop_capillary(a, flength, gas, pressure; λ0, τfwhm, energy, λlims, trange,
                     plasma=false, kerr=false, status_period=0)
```

Fixes #270

### CODE REVIEW

File: src/RK45.jl [hunk 1]
```diff
@@ -371,14 +372,18 @@ function stepcontrolPI!(s)
     β2 = -1/5 / 5
     ε = 0.8
     if s.ok
-        s.errlast == 0 && (s.errlast = s.err)
-        fac = s.safety * (ε/s.err)^β1 * (ε/s.errlast)^β2
+        s.errlast == 0 && (s.errlast = s.err) # if last error is zero, use current error instead
+        if s.errlast == 0 || s.err == 0
```
Comment (jtravs) [inline src/RK45.jl:376]: why do you need the `||` here? if `s.errlast == 0` then it gets reset in the line above. So we just need `if s.err == 0`?

**Review by jtravs — APPROVED** [review]

File: src/RK45.jl (hunk 1 above)
Comment (chrisbrahms) [reply src/RK45.jl:376]: I was too lazy to think throught the possible cases.
